Add smoke test

diff --git a/.github/workflows/deploy-assets.yml b/.github/workflows/deploy-assets.yml
--- a/.github/workflows/deploy-assets.yml
+++ b/.github/workflows/deploy-assets.yml
@@ -104,3 +104,62 @@ jobs:
         with:
           resource_group: ${{ env.DEPLOYMENT_RESOURCE_GROUP_NAME }}
           environment_tag: staging
+
+  test:
+    name: Smoke Test
+    runs-on: ubuntu-latest
+    needs: [staging]
+    environment:
+      name: Staging
+    steps:
+      # Checkout the repository to the GitHub Actions runner
+      - name: Checkout repo
+        uses: actions/checkout@v4
+
+      # Download output from deployment
+      - uses: actions/download-artifact@v4
+        with:
+          name: staging-artifacts
+
+      # Set Databricks host and token environment variables and  MLFlow tracking URI
+      - name: Set Databricks environment variables
+        uses: azure/cli@v2
+        with:
+          azcliversion: ${{ env.AZ_CLI_VERSION }}
+          inlineScript: |
+            DATABRICKS_WORKSPACE_NAME=$(az resource list --resource-group ${{ env.DEPLOYMENT_RESOURCE_GROUP_NAME }} \
+              | jq '.[] | select(.type == "Microsoft.Databricks/workspaces" and .tags.environment == "staging") | .name' -r)
+
+            echo "DATABRICKS_HOST=https://$(az databricks workspace show --name $DATABRICKS_WORKSPACE_NAME \
+              --resource-group ${{ env.DEPLOYMENT_RESOURCE_GROUP_NAME }} | jq '.workspaceUrl' -r)" >> $GITHUB_ENV
+              
+            echo "DATABRICKS_TOKEN=$(az account get-access-token \
+              --resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d | jq .accessToken -r)" >> $GITHUB_ENV
+      
+      # Set endpoint name
+      - name: Set endpoint name
+        run: |
+          echo "ENDPOINT_NAME=$(yq eval '.variables.endpoint_name.default' databricks/serving_endpoint.yml -r)" >> $GITHUB_ENV
+
+      # Smoke test the deployed container app
+      - name: Smoke test
+        run: |
+          # Exit on error
+          set -e
+          
+          STATUS_CODE=$(curl -X POST "$DATABRICKS_HOST/serving-endpoints/$ENDPOINT_NAME/invocations" \
+            -H "Content-Type: application/json" \
+            -u token:$DATABRICKS_TOKEN \
+            -d@databricks/src/sample-request.json \
+            -o response.json \
+            -w "%{http_code}" \
+            -s)
+
+          # Check the status code
+          if [ $STATUS_CODE -ne 200 ]; then
+              echo "Got status code $status instead of expected 200"
+              exit 1
+          fi
+
+          # Display the response
+          cat response.json
